### ISSUE TITLE
Does mkProperty really emit propertyChanged?

### ISSUE THREAD

**Issue by jkarni** [Philonous/d-bus#10]
The documentation for `mkProperty` states:

> Create a property from a getter and a setter. It will emit a PropertyChanged signal when the setter is called. To 
> change this behaviour modify the propertyEmitsChangedSignal field

But the code doesn't seem to call `propertyChanged` or otherwise emit the signal (and as far as I can tell from my application, indeed this isn't emitted). 

This affects `mkTVarProperty` too, which uses `mkProperty`.

**Comment by Philonous** [comment]
Yes, this seems to be a bug. I'll look into it.

**Comment by jkarni** [comment]
Looks like 658c0167e9451576c9ff545a4f0b7739d61dde1e fixed this - could you make a release with it?

Thanks a lot, for the fix and for the library!

**Comment by Philonous** [comment]
Done
